# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/HSC/HSC/HSC.srcs/sources_1/bd/system/ip/system_TOP_0_1/system_TOP_0_1.xci
# IP: The module: 'system_TOP_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: D:/HSC/HSC/HSC.srcs/sources_1/ip/ila_0_3/ila_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ila_0 || ORIG_REF_NAME==ila_0} -quiet] -quiet

# XDC: d:/HSC/HSC/HSC.gen/sources_1/ip/ila_0_3/ila_v6_2/constraints/ila_impl.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==ila_0 || ORIG_REF_NAME==ila_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: d:/HSC/HSC/HSC.gen/sources_1/ip/ila_0_3/ila_v6_2/constraints/ila.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==ila_0 || ORIG_REF_NAME==ila_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: d:/HSC/HSC/HSC.gen/sources_1/ip/ila_0_3/ila_0_ooc.xdc

# XDC: d:/HSC/HSC/HSC.gen/sources_1/bd/system/ip/system_TOP_0_1/system_TOP_0_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_TOP_0_1'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: D:/HSC/HSC/HSC.srcs/sources_1/bd/system/ip/system_TOP_0_1/system_TOP_0_1.xci
# IP: The module: 'system_TOP_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: D:/HSC/HSC/HSC.srcs/sources_1/ip/ila_0_3/ila_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ila_0 || ORIG_REF_NAME==ila_0} -quiet] -quiet

# XDC: d:/HSC/HSC/HSC.gen/sources_1/ip/ila_0_3/ila_v6_2/constraints/ila_impl.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==ila_0 || ORIG_REF_NAME==ila_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: d:/HSC/HSC/HSC.gen/sources_1/ip/ila_0_3/ila_v6_2/constraints/ila.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==ila_0 || ORIG_REF_NAME==ila_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: d:/HSC/HSC/HSC.gen/sources_1/ip/ila_0_3/ila_0_ooc.xdc

# XDC: d:/HSC/HSC/HSC.gen/sources_1/bd/system/ip/system_TOP_0_1/system_TOP_0_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_TOP_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
