set_property PACKAGE_PIN U20 [get_ports {AD_DA_0[0]}]
set_property PACKAGE_PIN T20 [get_ports {AD_DA_0[1]}]
set_property PACKAGE_PIN T19 [get_ports {AD_DA_0[2]}]
set_property PACKAGE_PIN U19 [get_ports {AD_DA_0[3]}]
set_property PACKAGE_PIN V20 [get_ports {AD_DA_0[4]}]
set_property PACKAGE_PIN W20 [get_ports {AD_DA_0[5]}]
set_property PACKAGE_PIN W19 [get_ports {AD_DA_0[6]}]
set_property PACKAGE_PIN W18 [get_ports {AD_DA_0[7]}]
set_property PACKAGE_PIN Y19 [get_ports {AD_DA_0[8]}]
set_property PACKAGE_PIN Y18 [get_ports {AD_DA_0[9]}]
set_property PACKAGE_PIN V18 [get_ports {AD_DA_0[10]}]
set_property PACKAGE_PIN V17 [get_ports {AD_DA_0[11]}]
set_property PACKAGE_PIN Y16 [get_ports {AD_DA_0[12]}]
set_property PACKAGE_PIN Y17 [get_ports {AD_DA_0[13]}]
set_property IOSTANDARD LVCMOS33 [get_ports {AD_DA_0[13]}]
set_property IOSTANDARD LVCMOS33 [get_ports {AD_DA_0[12]}]
set_property IOSTANDARD LVCMOS33 [get_ports {AD_DA_0[11]}]
set_property IOSTANDARD LVCMOS33 [get_ports {AD_DA_0[10]}]
set_property IOSTANDARD LVCMOS33 [get_ports {AD_DA_0[9]}]
set_property IOSTANDARD LVCMOS33 [get_ports {AD_DA_0[8]}]
set_property IOSTANDARD LVCMOS33 [get_ports {AD_DA_0[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {AD_DA_0[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {AD_DA_0[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {AD_DA_0[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {AD_DA_0[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {AD_DA_0[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {AD_DA_0[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {AD_DA_0[0]}]
set_property PACKAGE_PIN Y11 [get_ports {AD_DB_0[0]}]
set_property PACKAGE_PIN W11 [get_ports {AD_DB_0[1]}]
set_property PACKAGE_PIN Y13 [get_ports {AD_DB_0[2]}]
set_property PACKAGE_PIN Y12 [get_ports {AD_DB_0[3]}]
set_property PACKAGE_PIN V11 [get_ports {AD_DB_0[4]}]
set_property PACKAGE_PIN V10 [get_ports {AD_DB_0[5]}]
set_property PACKAGE_PIN W10 [get_ports {AD_DB_0[6]}]
set_property PACKAGE_PIN W9 [get_ports {AD_DB_0[7]}]
set_property PACKAGE_PIN Y9 [get_ports {AD_DB_0[8]}]
set_property PACKAGE_PIN Y8 [get_ports {AD_DB_0[9]}]
set_property PACKAGE_PIN Y7 [get_ports {AD_DB_0[10]}]
set_property PACKAGE_PIN Y6 [get_ports {AD_DB_0[11]}]
set_property PACKAGE_PIN W6 [get_ports {AD_DB_0[12]}]
set_property PACKAGE_PIN V6 [get_ports {AD_DB_0[13]}]
set_property IOSTANDARD LVCMOS33 [get_ports {AD_DB_0[13]}]
set_property IOSTANDARD LVCMOS33 [get_ports {AD_DB_0[12]}]
set_property IOSTANDARD LVCMOS33 [get_ports {AD_DB_0[11]}]
set_property IOSTANDARD LVCMOS33 [get_ports {AD_DB_0[10]}]
set_property IOSTANDARD LVCMOS33 [get_ports {AD_DB_0[9]}]
set_property IOSTANDARD LVCMOS33 [get_ports {AD_DB_0[8]}]
set_property IOSTANDARD LVCMOS33 [get_ports {AD_DB_0[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {AD_DB_0[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {AD_DB_0[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {AD_DB_0[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {AD_DB_0[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {AD_DB_0[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {AD_DB_0[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {AD_DB_0[0]}]
set_property PACKAGE_PIN R18 [get_ports AD_CTRL1_0]
set_property PACKAGE_PIN T17 [get_ports AD_CTRL2_0]
set_property PACKAGE_PIN U17 [get_ports AD_CTRL3_0]
set_property PACKAGE_PIN V7 [get_ports AD_RESET_0]
set_property PACKAGE_PIN U7 [get_ports AD_SCLK_0]
set_property PACKAGE_PIN U5 [get_ports AD_SDATA_0]
set_property PACKAGE_PIN T5 [get_ports AD_SEN_0]
set_property IOSTANDARD LVCMOS33 [get_ports AD_CTRL1_0]
set_property IOSTANDARD LVCMOS33 [get_ports AD_CTRL2_0]
set_property IOSTANDARD LVCMOS33 [get_ports AD_CTRL3_0]
set_property IOSTANDARD LVCMOS33 [get_ports AD_RESET_0]
set_property IOSTANDARD LVCMOS33 [get_ports AD_SCLK_0]
set_property IOSTANDARD LVCMOS33 [get_ports AD_SDATA_0]
set_property IOSTANDARD LVCMOS33 [get_ports AD_SEN_0]
set_property PACKAGE_PIN U14 [get_ports ad_clk_in_0]
set_property IOSTANDARD LVCMOS33 [get_ports ad_clk_in_0]
set_property PACKAGE_PIN N18 [get_ports clk_ad_out_0]
set_property IOSTANDARD LVCMOS33 [get_ports clk_ad_out_0]
set_property IOSTANDARD LVCMOS33 [get_ports clk_dir_0]
set_property IOSTANDARD LVCMOS33 [get_ports clk_in_0]
set_property PACKAGE_PIN H17 [get_ports clk_dir_0]
set_property PACKAGE_PIN H16 [get_ports clk_in_0]

set_property PACKAGE_PIN M14 [get_ports triger_in_pos_0]
set_property IOSTANDARD LVCMOS33 [get_ports triger_in_pos_0]
set_property PACKAGE_PIN K14 [get_ports triger_in_tr_0]
set_property IOSTANDARD LVCMOS33 [get_ports triger_in_tr_0]

#set_property IOSTANDARD LVCMOS33 [get_ports clk2_dir_0]
#set_property IOSTANDARD LVCMOS33 [get_ports clk_out_0]
#set_property PACKAGE_PIN K18 [get_ports clk2_dir_0]
#set_property PACKAGE_PIN K17 [get_ports clk_out_0]

#create_clock -period 10.000 -name ad_clk_in -waveform {0.000 5.000} [get_ports ad_clk_in]
#create_clock -period 10.000 -name ps_clk -waveform {0.000 5.000} [get_ports ps_clk]


#create_debug_core u_ila_0 ila
#set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_0]
#set_property ALL_PROBE_SAME_MU_CNT 1 [get_debug_cores u_ila_0]
#set_property C_ADV_TRIGGER false [get_debug_cores u_ila_0]
#set_property C_DATA_DEPTH 1024 [get_debug_cores u_ila_0]
#set_property C_EN_STRG_QUAL false [get_debug_cores u_ila_0]
#set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_0]
#set_property C_TRIGIN_EN false [get_debug_cores u_ila_0]
#set_property C_TRIGOUT_EN false [get_debug_cores u_ila_0]
#set_property port_width 1 [get_debug_ports u_ila_0/clk]
#connect_debug_port u_ila_0/clk [get_nets [list system_i/processing_system7_0/inst/FCLK_CLK0]]
#set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe0]
#set_property port_width 32 [get_debug_ports u_ila_0/probe0]
#connect_debug_port u_ila_0/probe0 [get_nets [list {system_i/TOP_0_data_num_cnt1[0]} {system_i/TOP_0_data_num_cnt1[1]} {system_i/TOP_0_data_num_cnt1[2]} {system_i/TOP_0_data_num_cnt1[3]} {system_i/TOP_0_data_num_cnt1[4]} {system_i/TOP_0_data_num_cnt1[5]} {system_i/TOP_0_data_num_cnt1[6]} {system_i/TOP_0_data_num_cnt1[7]} {system_i/TOP_0_data_num_cnt1[8]} {system_i/TOP_0_data_num_cnt1[9]} {system_i/TOP_0_data_num_cnt1[10]} {system_i/TOP_0_data_num_cnt1[11]} {system_i/TOP_0_data_num_cnt1[12]} {system_i/TOP_0_data_num_cnt1[13]} {system_i/TOP_0_data_num_cnt1[14]} {system_i/TOP_0_data_num_cnt1[15]} {system_i/TOP_0_data_num_cnt1[16]} {system_i/TOP_0_data_num_cnt1[17]} {system_i/TOP_0_data_num_cnt1[18]} {system_i/TOP_0_data_num_cnt1[19]} {system_i/TOP_0_data_num_cnt1[20]} {system_i/TOP_0_data_num_cnt1[21]} {system_i/TOP_0_data_num_cnt1[22]} {system_i/TOP_0_data_num_cnt1[23]} {system_i/TOP_0_data_num_cnt1[24]} {system_i/TOP_0_data_num_cnt1[25]} {system_i/TOP_0_data_num_cnt1[26]} {system_i/TOP_0_data_num_cnt1[27]} {system_i/TOP_0_data_num_cnt1[28]} {system_i/TOP_0_data_num_cnt1[29]} {system_i/TOP_0_data_num_cnt1[30]} {system_i/TOP_0_data_num_cnt1[31]}]]
#create_debug_port u_ila_0 probe
#set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe1]
#set_property port_width 18 [get_debug_ports u_ila_0/probe1]
#connect_debug_port u_ila_0/probe1 [get_nets [list {system_i/TOP_0_rd_data_count1[0]} {system_i/TOP_0_rd_data_count1[1]} {system_i/TOP_0_rd_data_count1[2]} {system_i/TOP_0_rd_data_count1[3]} {system_i/TOP_0_rd_data_count1[4]} {system_i/TOP_0_rd_data_count1[5]} {system_i/TOP_0_rd_data_count1[6]} {system_i/TOP_0_rd_data_count1[7]} {system_i/TOP_0_rd_data_count1[8]} {system_i/TOP_0_rd_data_count1[9]} {system_i/TOP_0_rd_data_count1[10]} {system_i/TOP_0_rd_data_count1[11]} {system_i/TOP_0_rd_data_count1[12]} {system_i/TOP_0_rd_data_count1[13]} {system_i/TOP_0_rd_data_count1[14]} {system_i/TOP_0_rd_data_count1[15]} {system_i/TOP_0_rd_data_count1[16]} {system_i/TOP_0_rd_data_count1[17]}]]
#create_debug_port u_ila_0 probe
#set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe2]
#set_property port_width 4 [get_debug_ports u_ila_0/probe2]
#connect_debug_port u_ila_0/probe2 [get_nets [list {system_i/TOP_0_state_data1[0]} {system_i/TOP_0_state_data1[1]} {system_i/TOP_0_state_data1[2]} {system_i/TOP_0_state_data1[3]}]]
#set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
#set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
#set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
#connect_debug_port dbg_hub/clk [get_nets clk]


create_clock -period 25.000 -name ad_clk_in_0 -waveform {0.000 12.500} [get_ports ad_clk_in_0]

set_false_path -from [get_clocks clk_fpga_0] -to [get_clocks -of_objects [get_pins system_i/TOP_0/U0/inst_ad_ctrl/inst_ads62p45/inst_ad_in_clk/mmcm_adv_inst/CLKOUT0]]
set_false_path -from [get_clocks -of_objects [get_pins system_i/TOP_0/U0/inst_ad_ctrl/inst_ads62p45/inst_ad_in_clk/mmcm_adv_inst/CLKOUT0]] -to [get_clocks clk_fpga_0]
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
connect_debug_port dbg_hub/clk [get_nets clk]
